[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[phases.setup]
nixPkgs = ["nodejs_18", "python3", "pip"]

[phases.install]
cmds = [
  "npm ci",
  "cd mcp-servers/servers && npm ci && npm run build"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"