[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
PORT = "4200"

[phases.setup]
nixPkgs = ["nodejs_20", "python3", "npm-9_x"]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit --omit=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"